#Application
application-name: @artifactId@
application-description: @project.description@
application-version: @project.version@
contact-name: Juli√°n Camilo Vega Rocha
contact-email: ingjulianvega@gmail.com
contact-url: https://twitter.com/ingjulianvega

spring:
  application:
    name: ssc-asu-intensity
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  #Cache
  cache:
    jcache:
      config: classpath:ehcache.xml
#General configuration
server:
  port: 8091
  servlet:
    context-path: /asu/v1/intensity
#Logging
#logging:
#  level:
#    root: DEBUG
#Exceptions
intensity:
  success: The operation was successful.
  prefix: 'API-INT:'
  error:
    general: There was an unexpected error. Please try again.

